### ISSUE TITLE
Change icon color for the different news source biases, disabled

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#31] opened 2017-03-27 02:15 UTC
Nice to have

**Comment by geraldgordinier** [comment] 2017-04-01 23:13
If user turns off spectrum, would be good to show a disabled gray icon

<img width="411" alt="screen shot 2017-04-01 at 4 13 18 pm" src="https://cloud.githubusercontent.com/assets/3990049/24583158/0c2ea76e-16f6-11e7-96b6-7295d894807d.png">

Otherwise change dependent on bias
<img width="83" alt="screen shot 2017-04-01 at 4 13 41 pm" src="https://cloud.githubusercontent.com/assets/3990049/24583162/1a97c308-16f6-11e7-818c-f08585c9a589.png">

I believe this includes both header icon and minimized icon

**Comment by cssherry** [comment] 2017-04-04 16:39
If they turn off spectrum, I would probably just remove the minimized icon all together.

**Comment by geraldgordinier** [comment] 2017-04-04 17:42
If off, show nothing in the bottom right corner. That is A+++.

But we could update to the gray state for the header icon?

**Comment by cssherry** [comment] 2017-05-31 07:14
this is duplicate of https://github.com/spectrum-app/spectrum_chrome_app/issues/39. Icon is now grayed out if spectrum disabled

**Comment by cssherry** [comment] 2017-05-31 07:15
Too much animation to change icon color for every news source, so just sticking with the gray for disabled or colored for active.

**Closed by cssherry** 2017-05-31 07:15 UTC
Labels: enhancement
